/*
 * generated by Xtext
 */
package org.csu.idl.xtext.scoping;

import org.csu.idl.idlmm.Container;
import org.csu.idl.idlmm.ForwardDef;
import org.csu.idl.idlmm.InterfaceDef;
import org.csu.idl.idlmm.TranslationUnit;
import org.csu.idl.idlmm.UnionDef;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class IDLScopeProvider extends AbstractDeclarativeScopeProvider {

	public IScope scope_UnionDef(UnionDef context, EReference reference) throws Exception {
		EObject ct = context.eContainer();
		return getContainerScope(ct, reference);
	}

	public IScope scope_InterfaceDef(InterfaceDef context, EReference reference) throws Exception {
		EObject ct = context.eContainer();
		return getContainerScope(ct, reference);
	}
	
	public IScope scope_InterfaceDef(ForwardDef context, EReference reference) throws Exception {
		EObject ct = context.eContainer();
		return getContainerScope(ct, reference);
	}

	public IScope scope_TypedefDef(Container context, EReference reference) throws Exception {
		try {
			IScope result = getDefaultScope(context, reference);
			return result;
		} catch (Exception e) {
			System.out.println("Exception: " + e.getMessage());
			e.printStackTrace();
			return null;
		}
	}

	public IScope scope_TypedefDef(TranslationUnit context, EReference reference) throws Exception {
		return getDefaultScope(context, reference);
	}

	public IScope scope_ExceptionDef(Container context, EReference reference) throws Exception {
		IScope result = getDefaultScope(context, reference);
		return result;
	}

	public IScope scope_Constant(Container context, EReference reference) throws Exception {
		return getDefaultScope(context, reference);
	}
	
	public IScope scope_Constant(TranslationUnit context, EReference reference) throws Exception {
		IScope sc = getDefaultScope(context, reference);
		return sc;
	}

	
	private IScope getContainerScope(EObject context, EReference reference) throws Exception {
		if (context instanceof Container)
			return getDefaultScope((Container)context, reference);
		else if (context instanceof TranslationUnit)
			return getDefaultScope((TranslationUnit)context, reference);
		return IScope.NULLSCOPE;
	}

	private IScope getDefaultScope(Container container, EReference reference) throws Exception {
		return this.delegateGetScope(container, reference);
	}

	private IScope getDefaultScope(TranslationUnit context, EReference reference) throws Exception {
		return this.delegateGetScope(context, reference);
	}
}
